name: "\U0001F41E Bug report"
description: Report something broken
projects:
  - "Ragnar-Oock/2"
labels:
  - bug
  - triage
assignees:
  - Ragnar-Oock
type: bug
body:
  - type: markdown
    attributes:
      value: |
        **Before You Start...**

        This form is only for submitting bug reports. 
        
        If you want to request a feature or anything else make a custom issue
        
        Also try to search for your issue - it may have already been answered or even fixed in the development branch.
        However, if you find that an old, closed issue still persists in the latest version,
        you should open a new issue using the form below instead of commenting on the old issue.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do to reproduce the problem ? Clear and concise reproduction instructions are important for 
        us to be able to triage your issue in a timely manner. Note that you can use 
        [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected ?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening ?
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Browser used
      description: Some bugs only happen in specific browsers, list those you reproduced the bug with and it's version
      render: shell
      placeholder: Chrome 143.0.7499.169, Firefox 146.0
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
